name: ee
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - earthengine-api
  - py6s
  - geemap
  - scipy
  - pip
  - pip:
    - pandas==1.3.3
    - parse==1.19.0
    - xarray==0.19.0  # for loading .nc
    - xarray[io]==0.19.0
#     - rio-tiler==2.1.3  # for streaming sat data


