name: ee
channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-tidyverse
  - python
  - numpy
  # GEE deps:
  # - earthengine-api
  # - py6s
  # - geemap
  - scipy
  - pip
  - pip:
    - matplotlib~=3.5.1
    - pandas~=1.3.3
    - parse~=1.19.0
    - xarray~=0.19.0  
    # - xarray[io]~=0.19.0  # for loading .nc
    # - rio-tiler~=2.1.3  # for streaming sat data
    - statsmodels~=0.13.0  # for ts seasonal decomp


